=== api-evangelist/activecampaign/json-schema/activecampaign-sms-broadcast-update-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/activecampaign/refs/heads/main/json-schema/activecampaign-sms-broadcast-update-request-schema.json",
  "title": "BroadcastUpdateRequest",
  "description": "BroadcastUpdateRequest schema from ActiveCampaign API",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "address_id": {
      "type": "integer",
      "nullable": true
    },
    "body": {
      "type": "string"
    },
    "media_urls": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "preview_url": {
      "type": "string",
      "format": "uri"
    },
    "shorten_track_links_enabled": {
      "type": "boolean"
    },
    "status": {
      "type": "string",
      "description": "Status of the broadcast. pending_review starts kicks off the broadcast to be sent",
      "enum": [
        "draft",
        "pending_review"
      ]
    },
    "scheduled_date": {
      "type": "string",
      "format": "date-time"
    },
    "sent_to_count": {
      "type": "integer"
    },
    "list_ids": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    },
    "segment_id": {
      "type": "string"
    },
    "custom_run_id": {
      "type": "string",
      "description": "custom run id generated from segmentMatchSome endpoint and passing a valid segment id",
      "format": "uuid",
      "nullable": true
    },
    "custom_segment_id": {
      "type": "string",
      "description": "custom segment id generated from segmentsV2 endpoint and passing in a valid audience",
      "format": "uuid",
      "nullable": true
    },
    "label_ids": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    }
  }
}

=== api-evangelist/activecampaign/examples/activecampaign-sms-broadcast-update-request-example.json
{
  "name": "Example Name",
  "address_id": 42,
  "body": "example-value",
  "media_urls": [
    "https://example.com/path/abc123"
  ],
  "preview_url": "https://example.com/path/abc123",
  "shorten_track_links_enabled": true,
  "status": "draft",
  "scheduled_date": "2025-03-15T14:30:00Z",
  "sent_to_count": 42,
  "list_ids": [
    42
  ],
  "segment_id": "500123",
  "custom_run_id": "550e8400-e29b-41d4-a716-446655440000",
  "custom_segment_id": "550e8400-e29b-41d4-a716-446655440000",
  "label_ids": [
    42
  ]
}
